name: subscriptionfairy
description: "A new Flutter project."

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Core
  freezed: ^2.4.6
  envied: ^0.5.3

  # Firebase
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

  # Utility
  persistent_bottom_nav_bar: ^5.0.2
  cached_network_image: ^3.3.1
  intl: ^0.18.1

  kartal: ^3.5.0

  # Date Time Picker
  syncfusion_flutter_datepicker: 24.1.45

  # Google
  json_annotation: ^4.8.1

  easy_localization: ^3.0.3

  gen:
    path: module/gen

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
